version: "2"
run:
  build-tags:
    - development
linters:
  default: all
  disable:
    - depguard # NA
    - err113 # TODO
    - exhaustruct
    - gochecknoglobals # we want some globals for now
    - nonamedreturns # we want named returns
    - paralleltest # TODO
    - testpackage
  settings:
    cyclop:
      package-average: 4
      max-complexity: 20
    decorder:
      disable-dec-num-check: true
      disable-dec-order-check: false
    errcheck:
      #severity: warn
      disable-default-exclusions: false
      check-type-assertions: true
      check-blank: true
    errchkjson:
      #severity: Warn
      report-no-exported: true
    errorlint:
      asserts: true
    exhaustive:
      check:
        - switch
        - map
      default-signifies-exhaustive: true
    funlen:
      ignore-comments: true
    gocritic:
      disabled-checks:
        - commentFormatting
        - exposedSyncMutex
        - commentedOutCode
      enabled-tags:
        - diagnostic
        - style
        - performance
        - experimental
        - opinionated
      settings:
        captLocal:
          paramsOnly: false
        elseif:
          skipBalanced: true
        nestingReduce:
          bodyWidth: 5
        rangeExprCopy:
          sizeThreshold: 512
          skipTestFuncs: true
        rangeValCopy:
          sizeThreshold: 201
          skipTestFuncs: true
        truncateCmp:
          skipArchDependent: true
        underef:
          skipRecvDeref: true
    godot:
      scope: all
      exclude:
        - ^ HAS_.*
        - ^ \[.*\]$
      capital: true
    gosec:
      config:
        G302: "0640"
        G306: "0640"
    govet:
      enable-all: true
      settings:
        shadow:
          strict: true
    ireturn:
      allow:
        - empty
        - error
        - stdlib
        - generic
    lll:
      line-length: 120
      tab-width: 1
    makezero:
      always: false
    nakedret:
      max-func-lines: 80
    nlreturn:
      block-size: 2
    nolintlint:
      require-explanation: true
      require-specific: true
      allow-unused: false
    prealloc:
      simple: true
      range-loops: true
      for-loops: false
    predeclared:
      qualified-name: false
    tagliatelle:
      case:
        rules:
          json: pascal
    thelper:
      test:
        first: true
        name: true
        begin: true
      benchmark:
        first: true
        name: true
        begin: true
      tb:
        first: true
        name: true
        begin: true
    unparam:
      check-exported: false
    unused:
      field-writes-are-uses: true
      post-statements-are-reads: false
      exported-fields-are-used: false
      parameters-are-used: true
      local-variables-are-used: false
      generated-is-used: false
    varnamelen:
      max-distance: 25
      min-name-length: 2
      check-receiver: false
      check-return: true
      check-type-param: true
      ignore-names:
        - err
        - db
        - T
      ignore-type-assert-ok: true
      ignore-map-index-ok: true
      ignore-chan-recv-ok: true
      ignore-decls:
        - i int
        - v reflect.Value
    wsl:
      strict-append: true
      allow-assign-and-call: true
      allow-multiline-assign: true
      force-case-trailing-whitespace: 0
      allow-trailing-comment: false
      allow-separated-leading-comment: false
      allow-cuddle-declarations: false
      force-err-cuddling: false
  exclusions:
    warn-unused: true
    generated: lax
issues:
  max-issues-per-linter: 0
  max-same-issues: 0
  new: false
  fix: false
formatters:
  enable:
    - gofmt
    - gofumpt
    - goimports
  settings:
    gofmt:
      simplify: true
    gofumpt:
      extra-rules: true
  exclusions:
    generated: lax
